### ISSUE TITLE
2025.3.0 - ImportError: cannot import name 'DeviceEntity' from 'pysmartthings'

### ISSUE THREAD

**Issue by Greminn** [samuelspagl/ha_samsung_soundbar#57]
Hi There, When you update to 2025.3.0 the integration will not load:

<img width="406" alt="Image" src="https://github.com/user-attachments/assets/8d7c84b2-dc30-4a42-a076-aa3d6b365294" />

Error log here: 

`
2025-03-06` 16:09:07.059 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'samsung_soundbar': Unable to import component: cannot import name 'DeviceEntity' from 'pysmartthings' (/usr/local/lib/python3.13/site-packages/pysmartthings/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/samsung_soundbar/__init__.py", line 8, in <module>
    from .api_extension.SoundbarDevice import SoundbarDevice
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 7, in <module>
    from pysmartthings import DeviceEntity
ImportError: cannot import name 'DeviceEntity' from 'pysmartthings' (/usr/local/lib/python3.13/site-packages/pysmartthings/__init__.py). Did you mean: 'DeviceEvent'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/samsung_soundbar/__init__.py", line 8, in <module>
    from .api_extension.SoundbarDevice import SoundbarDevice
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 7, in <module>
    from pysmartthings import DeviceEntity
ImportError: cannot import name 'DeviceEntity' from 'pysmartthings' (/usr/local/lib/python3.13/site-packages/pysmartthings/__init__.py). Did you mean: 'DeviceEvent'?
`

**Comment by jakeycrx** [comment]
I'm seeing the same error after updating to 2025.3.0

**Comment by Jor-Tech** [comment]
Maybe has to do with this?

Home Assistant release notes 2025.3:

_SmartThings 
The [SmartThings](https://www.home-assistant.io/integrations/smartthings) integration has been completely rewritten! 🎉 In December, **SmartThings shut down the old authentication method,** but thanks to SmartThings’ hard work and close collaboration with us, [@joostlek](https://github.com/joostlek) was able to bring back the integration is back—better than ever.

No more setting up routing, exposing ports, or creating developer accounts with access tokens—just log in with your Samsung account, and you’re good to go!

And there’s more! Push updates now work without exposing your instance to the internet, making the experience faster, seamless, and more secure! 🚀

A huge shoutout to our amazing community, who played a key role in this effort! 💙 When [@joostlek](https://github.com/joostlek) shared a guide on gathering test data, the community stepped up—sending in valuable test data that helped fine-tune the integration. This collaboration truly made a difference!_


source: https://www.home-assistant.io/blog/2025/03/05/release-20253/

**Comment by Greminn** [comment]
> Maybe has to do with this?
> 
> Home Assistant release notes 2025.3:

Yep - it looks like it could be. Just as a test, I installed the updated Smartthings integration and the onboarding flow works really well. I ended up with this with my Q950A soundbar:

<img width="673" alt="Image" src="https://github.com/user-attachments/assets/4c2e63ce-5aa9-43bb-bcff-1c47cce92627" />

**Comment by fbradyirl** [comment]
To fix for now, just pin the version in the manifest. 1.0.0 is not compatible with the addon.

Set to version [0.7.8](https://github.com/pySmartThings/pysmartthings/releases/tag/0.7.8)

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/16b35942-932e-46ed-b3cc-e017cc712bfc" />

```json
{
  "domain": "samsung_soundbar",
  "name": "Samsung Soundbar",
  "codeowners": [
    "@samuelspagl"
  ],
  "config_flow": true,
  "documentation": "https://www.example.com",
  "integration_type": "hub",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/samuelspagl/ha_samsung_soundbar/issues",
  "requirements": [
    "pysmartthings==0.7.8"
  ],
  "version": "0.4.1"
}
```

**Comment by Jor-Tech** [comment]
The temp fix works for this component, just not alongside the SmartThings integration as it will just load either one. I'll wait and hope for the new authentication method to be implemented 🙏

**Comment by vmonkey** [comment]
Or even better, get the additional features this integration provides into core :)

**Comment by jakeycrx** [comment]
Has anybody updated to 2025.3.1 yet?

**Comment by evilpig** [comment]
Came here to post this, getting same error. While the new smartthings integration does show my soundbar, doesn't allow advanced control. Would be nice if this could merge features with the official one.

**Comment by samuelspagl** [comment]
> Or even better, get the additional features this integration provides into core :)

Hi there ✌️ sorry for getting in touch with you just now. So generally yes that would also be my plan. I will try to take a look at the current implementation and how to implement it into core as soon as I get to it. Hopefully the coming of the week after. 

I that helps I can release a version with the pinned "pysmartthings" api sooner.

**Comment by diegocjorge** [comment]
> > Or even better, get the additional features this integration provides into core :)
> 
> Hi there ✌️ sorry for getting in touch with you just now. So generally yes that would also be my plan. I will try to take a look at the current implementation and how to implement it into core as soon as I get to it. Hopefully the coming of the week after.
> 
> I that helps I can release a version with the pinned "pysmartthings" api sooner.

Pinning the API might make things worse, not all users are aware of the problem and that would interfere with the official Smartthings integration (it loads either one, mostly random in my testing).

Have you taken a look at the new API? Would it require a lot of work to implement the changes?

**Comment by Lorislombardi** [comment]
hello @fbradyirl ,

Can you explain how I can apply this workaround ? I've edited the manifest and restarded my home assitant but I have the same issue.

**Comment by cklinkbeil** [comment]
Also seeing this issue. The only reason I used this HAC was because it allowed me to change the input on the soundbar.....the Native smartthings integration doesnt allow input changes.

**Comment by diegocjorge** [comment]
> hello [@fbradyirl](https://github.com/fbradyirl) ,
> 
> Can you explain how I can apply this workaround ? I've edited the manifest and restarded my home assitant but I have the same issue.

This only works if you have just the Soundbar integration. If you are running both the Soundbar and SmartThings integrations, one will start and the other will fail.

**Comment by diegocjorge** [comment]
Hey guys, I manage to make it work alongside the official SmartThings integration.

Basically, I grabbed the source code for pysmartthings API version 0.7.8, copied it to the `ha_samsung_soundbar` folder, and tweaked the files to import from this older version.

You can download the modified files here:
https://1drv.ms/u/c/8c751c99335dcd16/ERNZL8Ysa0VOtru-dKB_uX8Bp7y-hHvrWJDFXX6E8dH-0w?e=p9zJ2S

Copy the `pysmartthings_old` folder and paste it into:
`/config/custom_components/samsung_soundbar`

Replace these files with the updated ones:
```
/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py  
/config/custom_components/samsung_soundbar/__init__.py  
/config/custom_components/samsung_soundbar/config_flow.py  
/config/custom_components/samsung_soundbar/models.py  
```

Restart Home Assistant, and it should work.

This is just a quick fix until they update the integration to support the new pysmartthings API. I’m not a programmer—just figured this out using ChatGPT and some trial and error, so there’s probably a better way to do it.

<img width="238" alt="Image" src="https://github.com/user-attachments/assets/48f53eae-9944-46a2-aae2-bda83039ebb3" />

**Comment by smoldersonline** [comment]
Same here: Config flow could not be loaded ....

**Comment by jakeycrx** [comment]
2025.3.4 has just been released with this:

![Image](https://github.com/user-attachments/assets/b3dabba9-e451-48c9-a3ce-fe5dbd50de76)

Has anybody tried it yet?

**Comment by K900** [comment]
Upstream changes will not fix this integration. There's some work going on to allow soundbar controls with the upstream SmartThings integration.

**Comment by denysdovhan** [comment]
2025.4.0 still having the same problem. Can't even install this integration properly.

**Comment by K900** [comment]
2025.4.0 has native soundbar support in the built-in SmartThings integration.

**Comment by denysdovhan** [comment]
Weird, for me, it's just a `switch.soundbar` and `sensor.soundbar_volume`. No `media_player` entity was created after the update.

**Comment by K900** [comment]
What device is that? You might want to ask in the Discord.

**Comment by denysdovhan** [comment]
Samsung Ultra Slim Soundbar S801D

**Comment by K900** [comment]
Can you join the #soundbars room on https://discord.gg/yN5WvVaf? Would probably be faster to debug this live.

**Comment by denysdovhan** [comment]
Joined. Let's continue there.

**Comment by EarthEclipse** [comment]
Any updates?

**Comment by K900** [comment]
Use the upstream integration.

**Comment by jakeycrx** [comment]
> Use the upstream integration.

What about subwoofer control?

**Comment by K900** [comment]
Can probably be implemented with raw OCF commands as a workaround, but long term depends on Samsung exposing it in the API.

**Comment by EarthEclipse** [comment]
Uf, ok. I only used this integration to control the woofer (set to min/normal depending on time of day).

Thanks for having it working this long. :)

**Comment by jakeycrx** [comment]
> Uf, ok. I only used this integration to control the woofer (set to min/normal depending on time of day).
> 
> Thanks for having it working this long. :)

Exactly the same as me I also have it set to adjust the subwoofer when I play something via Plex as well

**Comment by K900** [comment]
I have a small integration here: https://gitlab.com/K900/nix/-/tree/master/machines/qb/hass/ocf-escape-hatch 

That adds a "send raw OCF command" action on top of the upstream SmartThings integration.

You can use that action with URL: `/sec/networkaudio/woofer` and payload `x.com.samsung.networkaudio.woofer: <the subwoofer level you want>`.

**Comment by meetic-daviddiai** [comment]
> Hey guys, I manage to make it work alongside the official SmartThings integration.
> 
> Basically, I grabbed the source code for pysmartthings API version 0.7.8, copied it to the `ha_samsung_soundbar` folder, and tweaked the files to import from this older version.
> 
> You can download the modified files here: https://1drv.ms/u/c/8c751c99335dcd16/ERNZL8Ysa0VOtru-dKB_uX8Bp7y-hHvrWJDFXX6E8dH-0w?e=p9zJ2S
> 
> Copy the `pysmartthings_old` folder and paste it into: `/config/custom_components/samsung_soundbar`
> 
> Replace these files with the updated ones:
> 
> ```
> /config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py  
> /config/custom_components/samsung_soundbar/__init__.py  
> /config/custom_components/samsung_soundbar/config_flow.py  
> /config/custom_components/samsung_soundbar/models.py  
> ```
> 
> Restart Home Assistant, and it should work.
> 
> This is just a quick fix until they update the integration to support the new pysmartthings API. I’m not a programmer—just figured this out using ChatGPT and some trial and error, so there’s probably a better way to do it.
> 
> <img alt="Image" width="238" src="https://private-user-images.githubusercontent.com/58111081/425140296-48f53eae-9944-46a2-aae2-bda83039ebb3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc0NzU4NjUsIm5iZiI6MTc2NzQ3NTU2NSwicGF0aCI6Ii81ODExMTA4MS80MjUxNDAyOTYtNDhmNTNlYWUtOTk0NC00NmEyLWFhZTItYmRhODMwMzllYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTAzVDIxMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTlkMDhhZmY0M2VhMDA5YTkzOGRkNTAyZGU4YTY0OWU2MzIwMjlmODU0ZmE3NDI1MDA0YjZmNDY4MmViMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.91fwSJzlKJ3LYi4mu3vqGgPBGRPpNlThVaSndlxpEnE">

Hello, 

Can you give again how you modified files please ?
The link you pasted isn't available anymore

Thanks
